-- 시나리오: retry 대표 검증 뒤 실행 근거를 확인하는 SQL 예시 파일
-- 적용 시점: 앱 종료 후에만 실행한다.
-- 선행 단계: 앱 기동 전 retry-source-execution-seed.example.sql 을 적용하고, 앱 기동 뒤 retry 요청을 실행한다.
-- 이번 단계에서는 확인 시점과 연결 순서만 고정하고, 실제 SELECT 구문은 후속 spec에서 정리한다.
