-- 시나리오: retry 대표 검증용 원본 실행 준비 데이터 예시 파일
-- 적용 시점: 앱 기동 전에 local H2에 먼저 넣는다.
-- 다음 단계: 앱 기동 뒤 retry 요청을 실행하고, 앱 종료 후 retry-runtime-evidence-check.example.sql 로 결과 row를 확인한다.
-- 이번 단계에서는 적용 시점과 연결 순서만 고정하고, 실제 INSERT 구문은 후속 spec에서 정리한다.
