package com.agilerunner.domain.exception;

public enum ErrorCode {
    GITHUB_INSTALLATION_ID_MISSING,
    OPENAI_CLIENT_MISSING,
    OPENAI_REVIEW_FAILED,
    GITHUB_APP_CONFIGURATION_MISSING,
    GITHUB_COMMENT_PREPARATION_FAILED,
    GITHUB_COMMENT_POST_FAILED
}
