CREATE TABLE IF NOT EXISTS TASK_STATE (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_key VARCHAR(255) NOT NULL,
    issue_number BIGINT,
    title VARCHAR(255) NOT NULL,
    status VARCHAR(32) NOT NULL,
    retry_count INT NOT NULL DEFAULT 0,
    owner_role VARCHAR(32),
    started_at TIMESTAMP,
    finished_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_task_state_task_key UNIQUE (task_key)
);

CREATE INDEX IF NOT EXISTS idx_task_state_issue_number ON TASK_STATE (issue_number);

CREATE TABLE IF NOT EXISTS EVALUATION_CRITERIA (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_key VARCHAR(255) NOT NULL,
    criteria_key VARCHAR(100) NOT NULL,
    category VARCHAR(32) NOT NULL,
    description CLOB NOT NULL,
    status VARCHAR(32) NOT NULL,
    evidence CLOB,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_evaluation_criteria_task_key UNIQUE (task_key, criteria_key)
);

CREATE INDEX IF NOT EXISTS idx_evaluation_criteria_task_key ON EVALUATION_CRITERIA (task_key);

CREATE TABLE IF NOT EXISTS REVIEW_RUN (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_key VARCHAR(255) NOT NULL,
    task_key VARCHAR(255) NOT NULL,
    delivery_id VARCHAR(255) NOT NULL,
    repository_name VARCHAR(255) NOT NULL,
    pull_request_number BIGINT NOT NULL,
    event_type VARCHAR(64) NOT NULL,
    action VARCHAR(64),
    status VARCHAR(32) NOT NULL,
    error_message CLOB,
    started_at TIMESTAMP NOT NULL,
    finished_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_review_run_run_key UNIQUE (run_key),
    CONSTRAINT uq_review_run_delivery_id UNIQUE (delivery_id)
);

CREATE INDEX IF NOT EXISTS idx_review_run_task_key ON REVIEW_RUN (task_key);
CREATE INDEX IF NOT EXISTS idx_review_run_pull_request_number ON REVIEW_RUN (pull_request_number);

CREATE TABLE IF NOT EXISTS AGENT_EXECUTION_LOG (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_key VARCHAR(255) NOT NULL,
    issue_number BIGINT,
    run_key VARCHAR(255),
    agent_role VARCHAR(32) NOT NULL,
    step_name VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL,
    input_summary CLOB,
    output_summary CLOB,
    error_message CLOB,
    payload_json CLOB,
    started_at TIMESTAMP,
    ended_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_agent_execution_log_task_key ON AGENT_EXECUTION_LOG (task_key);
CREATE INDEX IF NOT EXISTS idx_agent_execution_log_run_key ON AGENT_EXECUTION_LOG (run_key);
